baseurl = "https://deblnia.netlify.com"
title = "deblina"
languageCode = "en-us"

# Theme to use
theme = "simple-hugo-theme"

# Pagination
paginate = 3
paginatePath = "page"

# Google analytics
# googleAnalytics = ""

# Copyright
copyright = "Â© 2019 â€” Deblina Mukherjee â€” All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/academic/"
    name = "academic"
    weight = 1
  [[menu.main]]
    url = "/nonacademic/"
    name = "nonacademic"
    weight = 2
  [[menu.main]]
    url = "/projects/"
    name = "projects"
    weight = 3
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 4

  # Footer
  [[menu.footer]]
    url = "https://github.com/deblnia"
    name = "âŒ¨ï¸"
    weight = 1
  [[menu.footer]]
    url = "/posts/index.xml"
    name = "ğŸ“¢"
    weight = 2
  [[menu.footer]]
    url = "mailto:deblina@uchicago.edu"
    name = "ğŸ“§"
    weight = 3
  [[menu.footer]]
    url = "https://twitter.com/deblnia"
    name = "ğŸ¤"
    weight = 4


# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
